server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: MyNewPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  